#!/bin/sh
alpha=''
background='#282a36'
selection='#44475a'
comment='#6272a4'
yellow='#f1fa8c'
orange='#ffb86c'
red='#ff5555'
magenta='#ff79c6'
blue='#6272a4'
cyan='#8be9fd'
green='50fa7b'

i3lock \
  -c '#13141a' \
  --insidever-color=$selection$alpha \
  --insidewrong-color=$selection$alpha \
  --inside-color=$selection$alpha \
  --ringver-color=$green$alpha \
  --ringwrong-color=$red$alpha \
  --ring-color=$blue$alpha \
  --line-uses-ring \
  --keyhl-color=$magenta$alpha \
  --bshl-color=$orange$alpha \
  --separator-color=$selection$alpha \
  --verif-color=$green \
  --wrong-color=$red \
  --modif-color=$red \
  --layout-color=$blue \
  --date-color=$blue \
  --time-color=$blue \
  --screen 1 \
  --clock \
  --indicator \
  --time-str="%H:%M:%S" \
  --date-str="%A %e %B %Y" \
  --verif-text="" \
  --wrong-text="" \
  --noinput="" \
  --lock-text="" \
  --lockfailed="" \
  --time-pos="150:h-100" \
  --date-pos="150:h-70" \
  --ind-pos="300:h-100" \
  --time-size=48 \
  --date-size=18 \
  --radius=30 \
  --ring-width=9 \
  --pass-media-keys \
  --pass-screen-keys \
  --pass-volume-keys \
#  --time-font="JetBrainsMono Nerd Font" \
#  --date-font="JetBrainsMono Nerd Font" \
#  --layout-font="JetBrainsMono Nerd Font" \
#  --verif-font="JetBrainsMono Nerd Font" \
#  --wrong-font="JetBrainsMono Nerd Font" \
